# Generated by Django 5.0.6 on 2024-07-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_publicaciones_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
