# Generated by Django 5.0.6 on 2024-07-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_publicaciones_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
